# Generated by Django 3.0.3 on 2020-04-29 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languageprac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_vocab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languageprac.Vocabulary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languageprac.Record')),
            ],
        ),
    ]
