# Generated by Django 3.0.5 on 2020-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageprac', '0002_favouriterecord_favouritevocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('type_id', models.IntegerField()),
            ],
        ),
    ]
